// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Employee struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	Email  string `json:"email"`
	OktaID string `json:"okta_id"`
	Active bool   `json:"active"`
}

type Employeeoktagroup struct {
	EmployeeID    string `json:"employee_id"`
	OktaGroupName string `json:"okta_group_name"`
}

type Oktagroup struct {
	ID     int32          `json:"id"`
	Name   string         `json:"name"`
	OktaID sql.NullString `json:"okta_id"`
}
